apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Generate application release from template

on:
  push:
    branches:
      - '**'
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - name: Clone app code
        uses: docker://alpine/git:latest
        run: |
          git clone https://github.com/cb-demos/VacationRentals.git
      - name: Render release pipeline
        uses: docker://groovy
        run: |
          groovy render.groovy template.yaml VacationRentals/values.yaml >> release.yaml 2> /dev/null
          cat release.yaml
      - name: Clone runtime repo
        uses: docker://alpine/git:latest
        run: |
          git clone https://github.com/gmaxey/vacationRentalRuntime.git
      - name: Push release workflow to runtime repository
        if: "true"
        uses: docker://alpine/git:latest
        shell: sh
        run: |
          GITHUB_TOKEN=${{ secrets.VACATION_RUNTIME}}
          cd vacationRentalRuntime
          mkdir -p .cloudbees/workflows && cp ../release.yaml .cloudbees/workflows/ReleaseV1.yaml
          git add .cloudbees/workflows/ReleaseV1.yaml
          git commit . -m "Rendered ReleaseV1"
          git push